apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: l:/Service:dafault/nginx-app
  labels:
    app: nginx-app
  name: nginx-app
  namespace: dafault
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx-app
  type: ClusterIP