apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml    # ‚Üê Add this line!

images:
- name: nginx
  newName: nginx-app
  newTag: "19497703146"
